name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: github.com_BAAdeosun
      name: DFE-Digital/operations-devops-pipeline-templates
      ref: feature/stanalone-refactor
    - repository: config
      type: github
      endpoint: github.com_BAAdeosun
      name: DFE-Digital/login.dfe.config
      ref: master

trigger:
  branches:
    exclude:
    - master
    - develop
    - release/*
    - feature/*

variables:
- group: platform-global

stages:
- template: /Application/node/stages/signin-master-standalone-stage.yml@devopsTemplates
  parameters:
    applicationName: interactions
    resourceGroupSuffix: int